### ISSUE TITLE
[Bug]  Anyway to run this as docker-compose ?

### ISSUE THREAD

**Issue by PeterTucker** [coqui-ai/TTS#3745]
### Describe the bug

Anyway to run this as docker-compose ?

### To Reproduce

docker-compose up

### Expected behavior

N/A

### Logs

```shell
N/A
```

### Environment

```shell
N/A
```

### Additional context

N/A

**Comment by Xav-v** [comment]
Here is the docker-compose I use, after cloning this repo.

```
services:
  coqui:
    container_name: coqui
    image: ghcr.io/coqui-ai/tts
    build:
      context: ./TTS
    ports:
      - 5002:5002
    entrypoint: ["python3", "TTS/server/server.py", "--model_name", "tts_models/multilingual/multi-dataset/xtts_v2"]
    volumes:
      - ./tts:/root/.local/share
```
